name: Build MD AI APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Recuperer le projet
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Installer dependances Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo6 \
            cmake \
            libffi-dev \
            libssl-dev

      - name: Installer Buildozer
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install buildozer
          python -m pip install "cython<3"

      - name: Construire MD AI
        run: |
          buildozer android debug

      - name: Recuperer APK
        uses: actions/upload-artifact@v4
        with:
          name: MD-AI-APK
          path: bin/*.apk
